---
title: "Lecture 4 Homework"
format:
  html: 
    theme: literal
---

## Question 1

We have already learned about histograms, however in this homework we will learn to control their output.

-   Load beersheva.csv from moodle and plot a histogram of the column tempcmax.

-   Add the title "Max Temperature in Beersheva".

-   Name x-axis "Max Temp" and make the histogram to be gold-colored.

-   Make the histogram to have 9 breaks.

## Question 2

Histograms are great, however Kernal density plots are usually a much more effective way to view the distribution of a variable.

-   Create a kernel density plot from the same data as before

-   The plot should be with the same title as before, filled with light green color and a dark green border.

-   which one is better - histogram of kernel density plot?

## Question 3

let's check for outliers in the built-in mtcars dataset.

using the `dotchart` function do you think there are outliers in the horsepower column?

(Hint! you can use `boxplot` function to check your answer )


## Bonus question! That is for those who want to go further beyond!

Another good way to present this information is through a pie chart

-   Create a pie chart showing the proportion of cars from the mtcars data set that have different gear values. Hint! use the `pie()` function.

    ```{r, echo = FALSE}
    gears = table(mtcars$gear)

    percent = round(100*gears/sum(gears), 1)
    pielabels = paste(percent)
    pie(gears,col = rainbow(length(gears)), labels = percent , main = '% of Gears', cex = 0.8)
    legend("topright", c("Gear-3","Gear-4","Gear-5"), cex=0.8, fill=  rainbow(length(gears)))
    ```

___

A barplot is one of the most common types of plot.

It shows the relationship between a numerical variable and a categorical variable.

For example, you can display the height of several individuals using a bar chart.

In our case we want to display the calculated columns (tempcmax, tempcmin, tempcmean, rhmean, wsmean, wdmean). 

-   Using `?barplot` read how to create a bar plot with vertical or horizontal bars.

-   Subset the data so you will have only the needed columns.

-   Use colMeans on the created data and create a barplot.

-   Add The title "Beersheva Means"

-   x axis name as "Categories"

-   Line width of 5

-   Each bar will be with different color of your choice - to see all colors in R go to:

    <http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf>
