---
title: "Lecture 3 Answers"
format:
  html: 
    theme: literal
---

## Quastion 1

Use the `read.csv` function in Rstudio to read the whale data file.

```{r}
whaledata = read.csv("C:\\Users\\97253\\Documents\\l3\\whaledata.csv")
```

or you can try this option:

```{r}
whaledata = read.csv("C:/Users/97253/Documents/l3/whaledata.csv")

```

___

Use the read_csv function in Rstudio to read the whale data file from your working directory.

first we will find our working directory.

```{r,eval=FALSE}
getwd()
```

Now when the whale data is in our working directory, reading new files is much easier.

```{r, warning=FALSE, message = FALSE}
library(readr)
whaledata = read_csv("whaledata.csv")
```

___

## Quastion 2

```{r, eval=FALSE}
head(whaledata)
# The function Prints the first six rows of the data
head(whaledata, n=20)
# The function Prints the first twenty rows of the data
tail(whaledata)
# The function Prints the last six rows of the data
colnames(whaledata)
# The function Prints the names of the columns of the data in its original order
str(whaledata)
#The function displays the internal structure of an R object compactly.
summary(whaledata)
#The function computes summary statistics of data and model objects.
length(whaledata$gradient)
#The function shows how many values are in the vector.

```

## Quastion 3

```{r, eval=FALSE}
whale_new = whaledata[1:10, 1:4]
# first 10 rows and first 4 columns

whale_spec = whaledata[, c(1, 3, 4)] 
#First way

whale_spec = whaledata[, c("month", "water.noise", "number.whales")]    
#second way

whale_month_may = whaledata[1:50, ]  
# first 50 rows and all columns

whale.last = whaledata[-c(1:10), -8]  
# excluding first 10 rows and last column using negative indexing

whale.last = whaledata[-c(1:10), -c(ncol(whale))] 
# more general way if you have lots of columns

whale.last = whaledata[-c(1:10), -c("gradient")]   
# NOTE: this doesn't work for named columns


```

## Question 4

```{r, echo=FALSE}
whaledata = read.csv("whaledata.csv")
```


```{r}
whaledata.1200 <- whaledata[whaledata$depth > 1200, ]

whaledata.200 <- whaledata[whaledata$gradient > 200, ]

whaledata.low <- whaledata[whaledata$water.noise == "low", ]

whaledata.h.may <- whaledata[whaledata$water.noise == "high" & whaledata$month == "May", ]

whaledata.subset <- whaledata[whaledata$month == "October" & whaledata$water.noise == "low" & whaledata$gradient > 132, ]

whaledata.lat.long <- whaledata[whaledata$latitude > 60 & whaledata$latitude < 61 & whaledata$longitude > -6 & whaledata$longitude < -4, ]

whaledata.nomed <- whaledata[whaledata$water.noise != "medium", ]

whaledata.new <- whaledata[whaledata$depth > 1500 & whaledata$number.whales > mean(whaledata$number.whales, na.rm = TRUE), ]

#the variable number.whales contains 1 NA value. By default the mean function will return an NA. we will use the na.rm argument to ignore NAs.

```


