---
title: "Lecture 3 Exercises"
format:
  html: 
    theme: literal
---

## Question 1

Open a new folder on your personal computer named l3, into the new folder save the whale data file.

-   Use the `read.csv` function in Rstudio to read the whale data file.

------------------------------------------------------------------------

Using the `getwd()` function get your working directory location, and afterward copy the whale data file to your **working directory**.

If we need to read a big file, sometimes it will be better to use functions from different libraries. In this case, we want to use the package readr to read the same file as before. Install the package if needed, load it to R.

-   Use the `read_csv` function in Rstudio to read the whale data file from **your working directory**.

## Question 2

After uploading a csv file to R, the best thing to do is to examine it.

Try the following functions and write down what the outcome means.

head(whaledata)

head(whaledata, n=20)

tail(whaledata)

colnames(whaledata)

str(whaledata)

summary(whaledata)

length(whaledata\$gradient)

## Question 3

As part of your research on whales, you want to focus on specific information.

-   Extract all the elements of the first 20 rows and the first 4 columns of the whaledata and assign them to a new variable called whale_new.

-   Next, extract all observations (remember - rows) from the whale dataframe and the columns month, water.noise, and number.whales and assign them to a variable called whale_spec. (Do this in 2 ways, the first way by the specific number of columns and the second way by the names of the columns.)

-   Now, extract the first 50 rows and all columns from the original dataframe and assign them to a variable whale_month_may

-   Finally, extract all rows except the first 10 rows and all columns except the last column. Remember, for some of these questions you can specify the columns you want either by position or by name. Practice both ways.

## Question 4

Extract rows from the whale data frame based on the following criteria:

-   depths greater than 1200 m.

-   gradient steeper than 200 degrees.

-   water noise level of 'low'.

-    water.noise level of 'high' in the month of 'May'.

-   The month of 'October', water noise level of 'low' and gradient
    greater than the median value of gradient (132).

-   all observations from between latitudes 60.0 and 61.0 and longitudes
    -6.0 and -4.0.

-   all rows that do not have a water noise level of medium.

-   depths greater than 1500 m and with a greater number of whales
    spotted than average.

