---
title: "Lesson 3 Exercises"
author: "Introduction to Data Science"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

## Part 1

Open a new folder on your personal computer named l3, into the new folder save the whale data file.
Use the read.csv function in Rstudio to read the file.

## Part 2

Using the getwd() get your working directory location, and afterward copy the whale data file to your working directory.
Use the read.csv function in Rstudio to read the file.

## Part 3

If we need to read a big file, sometimes it will be better to use functions from different libraries. In this case, we want to use the package readr to read the same file as before. Install the package if needed, load it to R and read the quakes file using read_csv().

## Part 4

After uploading a csv file to R, the best thing to do is to examine it.

Try the following functions and write down what the outcome means.

head(whaledata)

head(whaledata, n=20)

tail(whaledata)

colnames(whaledata)

str(whaledata)

## Part 5

How many observations does this dataset have? How many variables are in this dataset? What type of variables are month and water.noise?


## Part 6

As part of your research on whales, you want to focus on specific information.

* Extract all the elements of the first 20 rows and the first 4 columns of the whaledata and assign them to a new variable called whale.sub.

* Next, extract all observations (remember - rows) from the whale dataframe and the columns month, water.noise, and number.whales and assign them to a variable called whale.num. (Do this in 2 ways, the first way by the specific number of columns and the second way by the names of the columns.)

* Now, extract the first 50 rows and all columns form the original dataframe and assign them to a variable whale.may 

## Part 7 

Create a matrix with 20 rows and 5 columns, containing the numbers 1 up to 100, Convert the matrix file to a data frame file. **In addition use one function that returns the number of rows and columns of the data.**

## Part 8 

Create the following vector:

v <- c(42, 92, 39, 19, 12, 16, 2, 0, 8.5, 50, 4,
           13, 0, -4, 9, 10, 0, 3, 9, 32, 28, 7, 11,
           -3, 8, 74, 70, 12, 20, -1, 6.7, 52, 6, 3, 
           -1, 1, 0, 5, 42, -0.2, 17, 3.1, -5, 11, 1,
           51, 46, 2, 51, 13, 1, 0, 30, -5, 9, 10)
           
What is the length of the vector?           

## Part 9 

Create a new data frame named noise_location that contains latitude, longitude, and water.noise columns from whaledata. In addition save the lnoise_location data frame in .csv format to your local folder.


## Part 10 

Save your entire workspace, naming it the third_lesson, afterwards upload the third_lesson file back into R. 









