---
title: "Lecture 5 Answers"
format:
  html: 
    theme: literal
editor_options: 
  markdown: 
    wrap: sentence
---

## Answer 1

```{r}
x <- c(7,5,2,11,2,3,6,0,1,4,8,9,5,12,11,5,1,0,2,2,7,3,10,19,18,
          9,20,14,15,1,16,9,13,0,0,2,11,3,4,1,7,9,10,5,3,4,13,15,
          19,14,2,4,1,12,15,12,11,10,7,4,11,8,1,11,2,3,0,12,17,21)
y <- c(1:3)
```

```{r}
#How many elements are in x?
length(x)

#Try to think what will be the result of:  y > 2 & y-1 == 2 
y > 2 & y-1 == 2

#How many elements in x are equal or bigger than 10?
length(x[x >= 10])

#How many elements in x are bigger than 8 and smaller than 14?
length(x[x > 8 & x < 14])

```

___

```{r}

type <- c("Smart", "3D", "Smart", "Smart", "4K", "4K", "3D", "Smart", "4K", "3D")
size <- c(45, 50, 45, 40, 50, 50, 40, 38, 50, 50)
price <- c(3000, 4200, 3500, 3000, 5200, 5100, 3800, 2400, 5100, 4200)

#Create a data frame from the vectors above
d = data.frame(type, size, price)

#How many repeated observations are in the data frame?
#You can notice that there are 2 TRUE, which means two duplicated observations.
duplicated(d)

# A better solution
length(duplicated(d)[duplicated(d) == TRUE])

#Create a cleaned data frame without the repeated observations
cleaned.d = unique(d)

#Another solution :)
cleaned.d = d[!duplicated(d), ]

```

## Answer 2

```{r}

#Download and read the forbes2000 file in R
forbes = read.csv("Forbes2000.csv")

#What is the maximum value of assets?
max(forbes$assets)

#What is the minimum of sales?
min(forbes$sales)

#What is the mean of profits?
mean(forbes$profits, na.rm = TRUE)

#How many NA's there are in profits?
nrow(forbes[is.na(forbes$profits),])

#More simple answer :)
sum(is.na(forbes$profits))

#Is there any company that appears twice in the forbes list?

sum(duplicated(forbes$name))

#There are no duplicated names


```

## Answer 3

```{r, eval=FALSE}

#Use summary only on companies with higher market value than the market value mean (of all companies)

summary(subset(forbes, marketvalue > mean(marketvalue)))

#another way without subset

summary(forbes[forbes$marketvalue > mean(forbes$marketvalue),])

#Use rescale to create a new column named marketvalue.rescaled in the forbes2000 data. (use the package scales)

library(scales)
forbes$marketvalue.rescaled <- rescale(forbes$marketvalue)

#Use cut() to create the column marketvalue_cat, so you will have 3 categorical bins of “Low”, “Medium” and “High” for the marketvalue

forbes$marketvalue_cat <- cut(forbes$marketvalue, breaks = 3, labels = c("Low", "Medium", "High"))

```

```{r}
# Create and combine histograms for profits, assets and sales and see the differences

par(mfrow=c(1,3))
hist(forbes$profits)
hist(forbes$assets)
hist(forbes$sales)

```


